# Generated by Django 5.0.4 on 2024-04-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
